name: pmultiqc
description: A library for proteomics QC report based on MultiQC framework.
keywords:
  - MultiQC
  - QC
  - Proteomics
tools:
  - pmultiqc:
      description: |
        A library for proteomics QC report based on MultiQC framework.
        Use `task.ext.args` to pass additional arguments, e.g.:
        - `--quantms_plugin` for quantms/dia/tmt/lfq data
        - `--diann_plugin` for DIANN data
        - `--maxquant_plugin` for MaxQuant data
        - `--proteobench_plugin` for ProteoBench data
        - `--mzid_plugin` for mzID data
        - `--disable_table` to disable table plots
        - `--ignored_idxml` to ignore idxML files
        - `--contaminant_affix VALUE` to specify contaminant affix
        - `--quantification_method VALUE` to specify quantification method (used with quantms_plugin)
      homepage: https://github.com/bigbio/pmultiqc/
      documentation: https://github.com/bigbio/pmultiqc/
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'sample1' ]
  - results:
      type: directory
      description: |
        Directory containing results files to be analyzed by MultiQC
  - multiqc_config:
      type: file
      description: |
        MultiQC configuration file (optional)
      pattern: "*.yml"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'sample1' ]
  - report:
      type: file
      description: MultiQC report file
      pattern: "*.html"
  - quantmsdb:
      type: file
      description: |
        Sqlite3 database file storing protein, psm and quantification information (optional)
      pattern: "*.db"
  - data:
      type: file
      description: Plots created by MultiQC
      pattern: "*_data"
  - versions:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@Chengxin Dai"
